version: '3.7'
volumes:
  sfstorage:

services:
  shakenfist:
    build: .
    privileged: true
    network_mode: host
    restart: always
    devices:
      - "/dev/kvm:/dev/kvm"
    volumes:
      - "/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${SHAKENFIST_STORAGE_PATH}:${SHAKENFIST_STORAGE_PATH}"
      - "./ansible/files/libvirt.tmpl:${SHAKENFIST_STORAGE_PATH}/libvirt.tmpl:ro"
      - "./ansible/files/dhcp.tmpl:${SHAKENFIST_STORAGE_PATH}/dhcp.tmpl:ro"
    env_file:
      - .env
    environment:
      SHAKENFIST_SQL_URL: "mysql://sf:${SHAKENFIST_DB_PASSWORD}@${SHAKENFIST_DB_IP}/sf"
      SHAKENFIST_STORAGE_PATH: "${SHAKENFIST_STORAGE_PATH}"
    cap_add:
      - NET_ADMIN
      - MKNOD
    ports:
      - 13000:13000
