- name: Deploy infrastructure
  terraform:
    project_path: "{{ansible_root}}/terraform/gcp"
    state: present
    force_init: true
    variables:
      project: "{{project}}"
      ssh_user: "{{ssh_user}}"
      ssh_key: "{{ssh_key}}"
  register: terraform_out

- name: Add sf nodes
  add_host:
    hostname: "sf-{{node_idx+1}}"
    node_name: "sf-{{node_idx+1}}"
    ansible_ssh_host: "{{item}}"
    node_ip: "{{item}}"
    ansible_ssh_private_key_file: "{{ssh_key_filename|default(omit)}}"
    groups: hypervisors, primary, etcd_master
  loop: "{{terraform_out.outputs.sf_nodes_external_ip.value}}"
  loop_control:
    index_var: node_idx

- name: Log terraform hosts
  debug:
    var: "{{ groups['hypervisors'] | map('extract', hostvars) }}"
