- name: Build Container Image
  docker_image:
    name: shakenfist
    tag: latest
    source: build
    build:
      path: "{{role_path}}/../../../"
      dockerfile: "{{role_path}}/files/Dockerfile"
      rm: no  # Setting this to yes will make subsequent runs slower, but doesn't leave as much on the host

- name: Create temporary directory to store container image archive
  tempfile:
    state: directory
    suffix: build
  register: docker_image

- name: Register temp directory fact
  set_fact:
    docker_image_path: "{{ docker_image.path }}"
  run_once: true

- name: Export Container Image
  docker_image:
    name: shakenfist
    tag: latest
    source: local
    archive_path: "{{ docker_image_path }}/shakenfist.tar.gz"
